### ISSUE TITLE
Info on version differences

### ISSUE THREAD

**Issue by LotBlind** [jmimu/AITD_PakEdit#1]
Hey there, me and a friend have been studying the game for years now and we know a lot about it. Your TODO lists that you were going to look into version differences but we can save you some effort. I've written the stuff I know about down below. Us two (LotBlind and my friend tigrou) are mainly studying it for speedrun purposes over on Speed Demos Archive but it's resulted in all kinds of random knowledge some of which is found in the same guide I link to below.

---

If you want to know what the LIFEs and ANIMs are, you can get those from this file (LISTANIM and LISTANI2 are combined in it): https://drive.google.com/file/d/1mx95yMoi77_1p4K0sntxmWQNI3whBnD7/view?usp=sharing

The only differences between floppy and CD-ROM in the collider data (ETAGE) is listed here: https://kb.speeddemosarchive.com/Alone_in_the_Dark_(1-3)/Game_Mechanics_and_Glitches#KNOWN_VERSION_DIFFERENCES

Search for "small differences in the room/collider data".

The only difference in the ANIM data is one added ANIM that has no keyframes, just an offset, used to make climbing a little more consistent in the CD-ROM release it seems.

The only difference in the LIFE data, other than changes made to SFX and music, is that the code related to climbing and falling has been shuffled around a bit and some code was moved to a new LIFE, causing other LIFE numbers to be thrown off. I'm working on updating that part of the guide to reflect on this but here are my notes as of right now if you're interested:

"#552 FLOPPY vs. LIFE 552 and LIFE 559 (new) CD_ROM:
- ignoring all the lines that are the same in the same place
- Floppy version has these that CD-ROM doesn't:
** LIFE 549 directly from the first IF clause instead of first going to LIFE 559.
** INV directly from the same instead of getting it in LIFE 559.
** Control (VAR0) directly from same instead of getting it in LIFE 559.
** TRACKMODE 1 directly from same instead of getting it in LIFE 559.
- CD-ROM has these that floppy doesn't.
** PC ANIM_ALL_ONCE player_climbing_end (268) -> idling in the first IF clause.
*** This new ANIM, number 268, is instantaneous and has an offset of 57. This is probably intended to stop the player from being so likely to fall back down after climbing. The game makes sure it has finished in LIFE 559 before proceeding the same way as it would have in the floppy version."

It's very difficult to imagine these changes amount to any real gameplay differences other than what the new ANIM creates.

**Comment by jmimu** [comment]
Thank you for the information, I'll update the repo.

**Comment by atkotter** [comment]
The 3DO port of AITD is also compatible with the tool, so the pak file formats did not change much, if at all, between the CD-ROM release and the port.

**Comment by jmimu** [comment]
Ok, thank you!
